from __future__ import annotations

from pathlib import Path
import re
from typing import Any

from .errors import ImporterError
from .util import is_hex_digest

_TREE_FILE = re.compile(r"^\s*\[F\]\s+(.+?)\s*$")
_TREE_DIR = re.compile(r"^\s*\[D\]\s+(.+?)\s*$")
_HASH_LINE = re.compile(r"^([0-9a-f]{64})\s+\./(.+?)\s*$")


def parse_tree_hash_report(path: Path) -> dict[str, Any]:
    try:
        lines = path.read_text(encoding="utf-8", errors="strict").splitlines()
    except (OSError, UnicodeError) as exc:
        raise ImporterError(f"no se puede leer el informe: {exc}") from exc

    declared_entries = None
    declared_files = None
    for line in lines[:20]:
        match_entries = re.match(r"^Entradas\s*:\s*(\d+)\s*$", line)
        match_files = re.match(r"^Ficheros\s*:\s*(\d+)\s*$", line)
        if match_entries:
            declared_entries = int(match_entries.group(1))
        if match_files:
            declared_files = int(match_files.group(1))

    tree_marker = None
    hash_marker = None
    for index, line in enumerate(lines):
        if line.strip() == "ÁRBOL":
            tree_marker = index
        if line.strip() in ("SHA-256", "HASHES SHA-256", "HASHES"):
            hash_marker = index
    # Reports generated by the project use a line of '=' after each marker.
    if tree_marker is None:
        raise ImporterError("el informe no contiene la sección ÁRBOL")

    hashes: dict[str, str] = {}
    for line in lines:
        match = _HASH_LINE.match(line)
        if match:
            digest, relpath = match.groups()
            hashes[relpath] = digest

    # The indented tree is only needed for paths not present in the hash list.
    # Hash paths are authoritative for files. The tree renderer may shell-escape
    # spaces (e.g. ``Windows\ Kits``), so mixing both spellings creates false
    # duplicates.
    files: set[str] = set(hashes)
    tree_files: set[str] = set()
    directories: set[str] = set()
    stack: list[tuple[int, str]] = []
    in_tree = False
    for line in lines[tree_marker + 1:]:
        if line.strip() == "=====":
            in_tree = True
            continue
        if not in_tree:
            continue
        if _HASH_LINE.match(line):
            break
        match_file = _TREE_FILE.match(line)
        match_dir = _TREE_DIR.match(line)
        if not match_file and not match_dir:
            continue
        indentation = len(line) - len(line.lstrip(" "))
        name = (match_file or match_dir).group(1)
        while stack and stack[-1][0] >= indentation:
            stack.pop()
        parent = "/".join(item[1] for item in stack)
        relpath = f"{parent}/{name}" if parent else name
        if match_dir:
            directories.add(relpath)
            stack.append((indentation, name))
        else:
            tree_files.add(relpath)

    required = {
        "00_README.md",
        "01_JUGAR",
        "02_RUNNER",
        "03_PARCHES_APLICADOS",
        "04_NOTAS_TECNICAS",
        "05_PARTIDAS_GUARDADAS",
        "06_AISLAMIENTO_RED",
        "07_AUDITORIA_SEGURIDAD",
        "MANIFEST_SHA256.txt",
    }
    present_entries = files | directories | tree_files
    missing = sorted(required - present_entries)

    def matching(prefix: str, suffixes: tuple[str, ...] = ()) -> list[dict[str, str]]:
        result = []
        for relpath in sorted(files):
            if not relpath.startswith(prefix.rstrip("/") + "/"):
                continue
            if suffixes and not relpath.lower().endswith(suffixes):
                continue
            item = {"path": relpath}
            if relpath in hashes:
                item["sha256"] = hashes[relpath]
            result.append(item)
        return result

    game_archives = matching("01_JUGAR", (".tar.gz", ".tgz", ".tar"))
    game_archives = [
        item for item in game_archives
        if not item["path"].lower().endswith(".sha256")
    ]
    runners = matching("02_RUNNER", (".tar.gz", ".tgz", ".tar", ".tar.zst"))
    runners = [
        item for item in runners
        if not item["path"].lower().endswith(".sha256")
    ]
    save_archives = matching("05_PARTIDAS_GUARDADAS", (".zip", ".tar.gz"))
    save_archives = [
        item for item in save_archives
        if not item["path"].lower().endswith(".sha256")
    ]

    steam_api = [
        {"path": relpath, "sha256": hashes.get(relpath)}
        for relpath in sorted(files)
        if Path(relpath).name.lower() in ("steam_api64.dll", "steam_api.dll")
        and "/GBE-Standalone/" not in relpath
    ]
    appmanifests = [
        {"path": relpath, "sha256": hashes.get(relpath)}
        for relpath in sorted(files)
        if re.fullmatch(r"appmanifest_\d+\.acf", Path(relpath).name)
    ]

    return {
        "schema": 0,
        "source_type": "tree-hashes-report",
        "template": (
            "legacy-preservation-package-v1" if not missing else "unrecognized"
        ),
        "status": "recognized" if not missing else "incomplete",
        "entry_count": declared_entries or len(present_entries),
        "file_count": declared_files or len(files),
        "hashed_file_count": len(hashes),
        "missing_required_entries": missing,
        "game_archives": game_archives,
        "runner_archives": runners,
        "save_archives": save_archives,
        "appmanifests": appmanifests,
        "active_steam_api_candidates": steam_api,
        "modules": {
            "steamless": any(
                path.startswith("03_PARCHES_APLICADOS/steamless/")
                for path in files
            ),
            "eac_launcher_omission": any(
                path.startswith("03_PARCHES_APLICADOS/omision_eac/")
                for path in files
            ),
            "input": any(path.startswith("09_INPUT_Y_MANDO/") for path in files),
            "supplemental_content": any(
                path.startswith("08_CONTENIDO_ADICIONAL/") for path in files
            ),
        },
    }
